name: netflix
on:
    push:
        branches:
            - main
env:
    AWS_REGION: ap-southeast-2
jobs:
    Testing:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            
            - name: setup node.js
              uses: actions/setup-node@v4
              with:
                node-version: '16'
            - name: install dependency
              run: npm install 

    File_scan:
        needs: Testing
        runs-on: ubuntu-latest
        steps:
            - name: install trivy
              run: |
                trivy fs  . > trivy.txt


    